AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://mycodebucet/pdftotxt.zip
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::020510964414:role/lambda_s3'
      Environment:
        Variables:
          TARGET_BUCKET: tempsearch-content-store
      Layers:
        - 'arn:aws:lambda:us-east-1:020510964414:layer:tika:1'
